const mockData1 = [
    [
      "APERIOD",
      "APERIODC",
      "_PREP_xseq",
      "_PREP_seq",
      "ORDER",
      "_PREP_name",
      "_prep_label",
      "_TRTN",
      "_TRT",
      "_PREP_execord",
      "_PREP_macro",
      "_PREP_value",
      "AEBODSYS",
      "AEDECOD",
      "_PMF_numer",
      "_PMF_denom",
      "_PMF_pct",
      "_PMF_numerM"
    ],
    [
      "0_0 mockData 1",
      "OVERALL",
      "3",
      "3",
      "0",
      "LEVEL1",
      "XXX XXXX",
      "1",
      " XXX XX (0000) - XXX XX~ (X=00)",
      "0",
      "XXXXXXX",
      " 00 (00.0) 000",
      "XXX XXXX",
      "**XXXXX**",
      "0",
      "0",
      "0",
      "0"
    ],
    [
      "0",
      "OVERALL",
      "3",
      "3",
      "0",
      "LEVEL1",
      "XXX XXXX",
      "2",
      " XXX XX (0000) - XXX XX~ (X=00)",
      "0",
      "XXXXXXX",
      " 00 (00.0) 000",
      "XXX XXXX",
      "**XXXXX**",
      "0",
      "0",
      "0",
      "0"
    ],
    [
      "0",
      "OVERALL",
      "3",
      "3",
      "0",
      "LEVEL1",
      "XXX XXXX",
      "3",
      " XXX XX (0000) - XXX XX~ (X=00)",
      "0",
      "XXXXXXX",
      " 00 (00.0) 000",
      "XXX XXXX",
      "**XXXXX**",
      "0",
      "0",
      "0",
      "0"
    ],
    [
      "0",
      "OVERALL",
      "3",
      "3",
      "0",
      "LEVEL1",
      "XXX XXXX",
      "90",
      " XXXXX XXX XX - XXX XX~ (X=000)",
      "0",
      "XXXXXXX",
      " 00 (00.0) 000",
      "XXX XXXX",
      "**XXXXX**",
      "0",
      "0",
      "0",
      "0"
    ],
    [
      "0",
      "OVERALL",
      "3",
      "3",
      "0",
      "LEVEL1",
      "XXX XXXX",
      "99",
      " XXXXX~ (X=000)",
      "0",
      "XXXXXXX",
      "000 (00.0) 000",
      "XXX XXXX",
      "**XXXXX**",
      "0",
      "0",
      "0",
      "0"
    ]
  ]

  export default mockData1