const mockData2 = [
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "3",
      "_PREP_seq": "3",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXX XXXX",
      "_TRTN": "1",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": " 00 (00.0) 000",
      "AEBODSYS": "XXX XXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "3",
      "_PREP_seq": "3",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXX XXXX",
      "_TRTN": "2",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": " 00 (00.0) 000",
      "AEBODSYS": "XXX XXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "3",
      "_PREP_seq": "3",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXX XXXX",
      "_TRTN": "3",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": " 00 (00.0) 000",
      "AEBODSYS": "XXX XXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "3",
      "_PREP_seq": "3",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXX XXXX",
      "_TRTN": "90",
      "_TRT": " XXXXX XXX XX - XXX XX~ (X=000)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": " 00 (00.0) 000",
      "AEBODSYS": "XXX XXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "3",
      "_PREP_seq": "3",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXX XXXX",
      "_TRTN": "99",
      "_TRT": " XXXXX~ (X=000)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "000 (00.0) 000",
      "AEBODSYS": "XXX XXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "5",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "_TRTN": "1",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "5",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "_TRTN": "2",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "5",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "_TRTN": "3",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "5",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "_TRTN": "90",
      "_TRT": " XXXXX XXX XX - XXX XX~ (X=000)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "5",
      "ORDER": "0",
      "_PREP_name": "LEVEL1",
      "_prep_label": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "_TRTN": "99",
      "_TRT": " XXXXX~ (X=000)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "**XXXXX**",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "6",
      "ORDER": "0",
      "_PREP_name": "LEVEL2",
      "_prep_label": "XXXXXXX",
      "_TRTN": "1",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "XXXXXXX",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "6",
      "ORDER": "0",
      "_PREP_name": "LEVEL2",
      "_prep_label": "XXXXXXX",
      "_TRTN": "2",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "XXXXXXX",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "0",
      "APERIODC": "OVERALL",
      "_PREP_xseq": "5",
      "_PREP_seq": "6",
      "ORDER": "0",
      "_PREP_name": "LEVEL2",
      "_prep_label": "XXXXXXX",
      "_TRTN": "3",
      "_TRT": " XXX XX (0000) - XXX XX~ (X=00)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 0.0)   0",
      "AEBODSYS": "XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX",
      "AEDECOD": "XXXXXXX",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    },
    {
      "APERIOD": "6",
      "APERIODC": "CYCLE 6",
      "_PREP_xseq": "25",
      "_PREP_seq": "33",
      "ORDER": "0",
      "_PREP_name": "LEVEL2",
      "_prep_label": "XXXXXXXXXXX XXX-XXXXXXX XXXXXXX XXXXXXXXXXXX",
      "_TRTN": "99",
      "_TRT": " XXXXX~ (X=0)",
      "_PREP_execord": "0",
      "_PREP_macro": "XXXXXXX",
      "_PREP_value": "  0 ( 000)   0",
      "AEBODSYS": "XXX XXXXXXXXX",
      "AEDECOD": "XXXXXXXXXXX XXX-XXXXXXX XXXXXXX XXXXXXXXXXXX",
      "_PMF_numer": "0",
      "_PMF_denom": "0",
      "_PMF_pct": "0",
      "_PMF_numerM": "0"
    }
  ]

export default mockData2